# Generated by Django 3.0 on 2020-07-05 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_auto_20200705_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
