# Generated by Django 3.0 on 2020-07-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_city_added_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
